# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practical6
  pod 'QRCodeReader.swift', '~> 10.1.0'
  # pod 'QRCode'
  # pod 'QRCode', :git => 'https://github.com/aschuch/QRCode.git', :branch => 'master'
  # pod 'EFQRCode', '~> 5.1.6'
end
